# .github/workflows/ci.yml
name: Nx-CI

on: [push, workflow_dispatch]

jobs:
  nx-coordinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
      - name: Reset NX
        run: npx nx reset
      - name: Start Nx Cloud Agent Coordinator
        run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js"  --stop-agents-after="e2e-ci"
      - name: Start Tests
        env:
          PLAYWRIGHT_HTML_OPEN: never
          CURRENTS_RECORD_KEY: 0E1SjVuESGNYCmwO
          CURRENTS_PROJECT_ID: 1BiNnG
          CURRENTS_CI_BUILD_ID: ${{ github.run_id }}-${{ github.sha }}
        run: npx nx run-many --target=e2e-ci --verbose --parallel=3
      - name: Generate random name
        id: vars
        run: echo "random_name=playwright-report-$(uuidgen)" >> $GITHUB_OUTPUT

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.vars.outputs.random_name }}
          path: dist/.playwright/apps/**/test_output/

